---
- locale_gen:
    name: ja_JP.UTF-8
    state: present
- name: "set LANG to /etc/default/locale"
  template:
    src: default-locale.j2
    dest: /etc/default/locale
    owner: root
    group: root
    mode: 0644
