---
- lineinfile: dest=/etc/locale.gen regexp='ja_JP\.UTF-8' line='ja_JP.UTF-8 UTF-8'
  register: ja_jp_locale_gen
- command: env DEBIAN_FRONTEND=noninteractive dpkg-reconfigure locales
  when: ja_jp_locale_gen|changed
