# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ffuenf/debian-7.6.0-amd64"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../site.yml"
  end
end
